name:                naive
version:             0.1.0.0
github:              "pe200012/naive"
license:             BSD3
author:              "pe200012"
maintainer:          "pe1326263755@gmail.com"
copyright:           "2021 pe200012"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pe200012/naive#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- recursion-schemes
- data-fix
- llvm-hs-pure
- llvm-hs-pretty
- text
- process
- directory

library:
  source-dirs: src

ghc-options:
  - -O2
  - -Wall

executables:
  naive-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naive

tests:
  naive-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naive
